import React, { useState } from "react";
import {
  ChevronLeft,
  RefreshCw,
  Download,
  Copy,
  Check,
  FileText,
  Workflow,
  Code2,
  GitCommit,
  Share2,
  ExternalLink,
  BookOpen,
  Sparkles,
  Terminal
} from "lucide-react";
import { ArchitectureDiagram } from "../ArchitectureDiagram";

export function FeatureDocumentationView({
  feature,
  repoName = "main",
  onBack = () => {},
  onRegenerate = () => {},
  isRegenerating = false
}) {
  const [activeTab, setActiveTab] = useState("documentation");
  const [copied, setCopied] = useState(false);
  const [showRawMarkdown, setShowRawMarkdown] = useState(false);

  if (!feature) return null;

  const fid = feature.id || feature.feature_id || "feature";
  const fname = feature.name || feature.feature_name || "Feature Module";
  const summary = feature.summary || "Technical specification auto-generated by Commitology.";
  const category = feature.category || "General";
  const lastGenerated = feature.lastGenerated || "Live Decompiled Spec";

  // Derive dynamic components from primary_files_hint or category
  let componentsTable = [];
  if (feature.documentation?.componentsTable && feature.documentation.componentsTable.length > 0) {
    componentsTable = feature.documentation.componentsTable;
  } else if (feature.primary_files_hint && feature.primary_files_hint.length > 0) {
    componentsTable = feature.primary_files_hint.map((p) => {
      const base = p.split("/").pop();
      return {
        component: base.replace(/[-_.]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
        description: `Primary module file responsible for ${fname} logic and data flows.`,
        path: p
      };
    });
  } else {
    // Generate domain-specific components
    const cat = category.toLowerCase();
    if (cat.includes("auth") || cat.includes("security")) {
      componentsTable = [
        { component: "Auth Router", description: "Handles login, OAuth callback, and token issuance", path: "app/routes/auth_routes.py" },
        { component: "Security Guard", description: "JWT validation and user authentication dependency", path: "app/core/security.py" },
        { component: "User Model", description: "User entity and GitHub token persistence", path: "app/models/user.py" }
      ];
    } else if (cat.includes("db") || cat.includes("data") || cat.includes("model")) {
      componentsTable = [
        { component: "Database Engine", description: "SQLAlchemy engine connection pool and session maker", path: "app/database/database.py" },
        { component: "Data Models", description: "Relational entity declarations and column constraints", path: "app/models/user.py" }
      ];
    } else if (cat.includes("ai") || cat.includes("gemini")) {
      componentsTable = [
        { component: "LLM Categorizer", description: "Clusters raw commit diffs into semantic product features", path: "app/services/ai_feature_service.py" },
        { component: "Doc Synthesizer", description: "Generates Markdown architecture specifications", path: "app/services/ai_doc_service.py" }
      ];
    } else if (cat.includes("git") || cat.includes("repo")) {
      componentsTable = [
        { component: "GitHub Router", description: "Endpoint declarations for repos, commits, and authors", path: "app/routes/github_routes.py" },
        { component: "PyGithub Ingestion", description: "Fetches commits, diffs, and developer authorship", path: "app/services/github_functions.py" }
      ];
    } else {
      componentsTable = [
        { component: `${fname} Controller`, description: `Core business logic and state machine for ${fname}`, path: `app/services/${fid}.py` },
        { component: `${fname} Router`, description: `REST endpoints and request validation schemas`, path: `app/routes/${fid}_routes.py` }
      ];
    }
  }

  // Derive dynamic architecture labels
  let archLabels = {
    client: "Client Viewport (Web/Mobile)",
    service: `${fname} Gateway`,
    database: "Persistence Layer / DB",
    external: "External Protocols & APIs"
  };

  const catLower = category.toLowerCase();
  if (catLower.includes("auth")) {
    archLabels = {
      client: "Client Browser / OAuth",
      service: "Auth & JWT Security Service",
      database: "User & Session Store",
      external: "GitHub OAuth2 Provider"
    };
  } else if (catLower.includes("ai")) {
    archLabels = {
      client: "Commitology Cyberdeck",
      service: "Gemini 2.5 Flash Decompiler",
      database: "Knowledge Telemetry DB",
      external: "Google Generative AI"
    };
  } else if (catLower.includes("db")) {
    archLabels = {
      client: "Application Services",
      service: "SQLAlchemy ORM Service",
      database: "SQLite / Postgres Storage",
      external: "Migration Engine (Alembic)"
    };
  } else if (catLower.includes("git")) {
    archLabels = {
      client: "Telemetry Dashboard",
      service: "GitHub Ingestion Engine",
      database: "Commits Cache / DB",
      external: "GitHub REST API"
    };
  }

  // Derive dynamic endpoints
  let apiEndpoints = [];
  const cleanId = fid.replace(/[^a-z0-9_-]/gi, "");
  if (catLower.includes("auth")) {
    apiEndpoints = [
      { method: "GET", path: "/auth/github", desc: "Redirect to GitHub OAuth consent flow" },
      { method: "GET", path: "/auth/github/callback", desc: "Exchange OAuth code for user JWT" },
      { method: "GET", path: "/auth/me", desc: "Retrieve authenticated user profile" },
      { method: "POST", path: "/auth/logout", desc: "Revoke token and invalidate session" }
    ];
  } else if (catLower.includes("ai")) {
    apiEndpoints = [
      { method: "POST", path: "/ai/features/categorize", desc: "Analyze commits and decompile into feature clusters" },
      { method: "POST", path: "/ai/features/generate-doc", desc: "Extract diffs and synthesize <feature_name>.md" }
    ];
  } else if (catLower.includes("git")) {
    apiEndpoints = [
      { method: "GET", path: "/github/repos", desc: "Fetch user repositories from GitHub" },
      { method: "GET", path: "/github/repo/commits", desc: "Fetch repository commit history" },
      { method: "GET", path: "/github/repo/contributors", desc: "Compute repository contributors" }
    ];
  } else {
    apiEndpoints = [
      { method: "GET", path: `/api/${cleanId}`, desc: `Retrieve current state for ${fname}` },
      { method: "POST", path: `/api/${cleanId}`, desc: `Execute action or state transition for ${fname}` }
    ];
  }

  // Full dynamic Markdown content
  const markdownText =
    feature.markdown_content ||
    feature.documentation?.markdown ||
    `# Feature Documentation: ${fname}

## 1. Executive Summary & Purpose
${summary}

## 2. Architectural Overview & Workflow
The \`${fname}\` subsystem operates within the repository architecture as part of the **${category}** functional domain.
Client requests pass through the central API gateway and are processed by dedicated handlers before mutating storage or synchronizing with external telemetry.

## 3. Key Components
${componentsTable.map((c) => `- **${c.component}** (\`${c.path}\`): ${c.description}`).join("\n")}

## 4. API Endpoints
${apiEndpoints.map((e) => `- \`${e.method} ${e.path}\`: ${e.desc}`).join("\n")}

## 5. Verification & Testing
- Validated via unit test suites and repository commit SHA diff inspection.
- Edge cases handled: network interruptions, authorization failures, and schema serialization.
`;

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    const blob = new Blob([markdownText], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${fid}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-[#080a0f] overflow-hidden font-mono select-none">
      
      {/* Top Header & Breadcrumbs */}
      <div className="p-4 sm:p-5 border-b border-[#00ff66]/20 bg-[#0c0e16] shrink-0">
        <div className="flex items-center gap-1.5 text-[11px] text-slate-500 mb-2">
          <button
            onClick={onBack}
            className="flex items-center gap-1 text-[#00ff66] hover:underline"
          >
            <ChevronLeft className="h-3.5 w-3.5" />
            <span>Overview</span>
          </button>
          <span>/</span>
          <span className="text-slate-400">{repoName}</span>
          <span>&gt;</span>
          <span className="text-white font-bold">{fname}</span>
          <span>&gt;</span>
          <span className="text-[#ffb000]">[DOCS]</span>
        </div>

        {/* Feature Title & Action Buttons */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h1 className="text-base sm:text-lg font-black text-white tracking-wide flex items-center gap-2">
              <span>{fname}</span>
              <span className="text-[10px] px-2 py-0.5 rounded bg-black text-[#00ff66] border border-[#00ff66]/40 uppercase">
                {fid}.md
              </span>
            </h1>
            <p className="text-[11px] text-slate-400 mt-0.5">
              Spec Status: <span className="text-[#00ff66] font-bold">[DECOMPILED & VERIFIED]</span>
            </p>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={() => onRegenerate(feature)}
              disabled={isRegenerating}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-black border border-[#00e5ff] text-[#00e5ff] text-xs font-bold hover:bg-[#00e5ff] hover:text-black transition"
            >
              <RefreshCw className={`h-3.5 w-3.5 ${isRegenerating ? "animate-spin text-[#00e5ff]" : ""}`} />
              <span>{isRegenerating ? "[SYNTHESIZING...]" : "[REGENERATE AI SPEC]"}</span>
            </button>

            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded border border-[#00ff66] text-[#00ff66] hover:bg-[#00ff66] hover:text-black text-xs font-bold transition"
            >
              {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? "[COPIED!]" : "[COPY MD]"}</span>
            </button>

            <button
              onClick={handleExport}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-[#ffb000] text-black text-xs font-bold border border-white hover:bg-white transition"
            >
              <Download className="h-3.5 w-3.5 text-black" />
              <span>[EXPORT .MD]</span>
            </button>
          </div>
        </div>

        {/* View Mode Pills */}
        <div className="flex items-center gap-4 mt-3 border-b border-white/5 text-xs font-semibold">
          <button
            onClick={() => setShowRawMarkdown(false)}
            className={`pb-1.5 transition relative ${
              !showRawMarkdown ? "text-[#00ff66] font-bold" : "text-slate-400 hover:text-white"
            }`}
          >
            [RENDERED VIEW]
            {!showRawMarkdown && <span className="absolute bottom-0 left-0 right-0 h-0.5 bg-[#00ff66]" />}
          </button>
          <button
            onClick={() => setShowRawMarkdown(true)}
            className={`pb-1.5 transition relative ${
              showRawMarkdown ? "text-[#00ff66] font-bold" : "text-slate-400 hover:text-white"
            }`}
          >
            [RAW MARKDOWN]
            {showRawMarkdown && <span className="absolute bottom-0 left-0 right-0 h-0.5 bg-[#00ff66]" />}
          </button>
        </div>
      </div>

      {/* Main Split Body */}
      <div className="flex-1 flex overflow-hidden">
        
        {/* Content Reading Area */}
        <div className="flex-1 overflow-y-auto p-5 space-y-6 bg-[#080a0f]">
          {showRawMarkdown ? (
            <div className="p-4 rounded-xl bg-black border border-slate-800">
              <pre className="text-xs text-[#00ff66] whitespace-pre-wrap leading-relaxed select-text font-mono">
                {markdownText}
              </pre>
            </div>
          ) : (
            <>
              {/* 1. Overview */}
              <section className="space-y-2">
                <h2 className="text-sm font-bold text-white flex items-center gap-2">
                  <span className="text-[#ffb000]">1.</span>
                  <span>Executive Summary & Purpose</span>
                </h2>
                <div className="p-3.5 rounded-xl bg-[#0c0e16] border border-white/5 text-xs text-slate-300 leading-relaxed font-mono">
                  {summary}
                </div>
              </section>

              {/* 2. Architecture */}
              <section className="space-y-2">
                <h2 className="text-sm font-bold text-white flex items-center gap-2">
                  <span className="text-[#ffb000]">2.</span>
                  <span>System Design & Topology</span>
                </h2>
                <ArchitectureDiagram
                  clientLabel={archLabels.client}
                  serviceLabel={archLabels.service}
                  databaseLabel={archLabels.database}
                  externalLabel={archLabels.external}
                />
              </section>

              {/* 3. Key Components */}
              <section className="space-y-2">
                <h2 className="text-sm font-bold text-white flex items-center gap-2">
                  <span className="text-[#ffb000]">3.</span>
                  <span>Key Components & Files</span>
                </h2>

                <div className="overflow-x-auto rounded-xl border border-white/5 bg-[#0c0e16]">
                  <table className="w-full text-left text-xs">
                    <thead>
                      <tr className="border-b border-white/5 bg-black/40 text-slate-400 text-[10px] uppercase">
                        <th className="py-2.5 px-3">Component</th>
                        <th className="py-2.5 px-3">Description</th>
                        <th className="py-2.5 px-3">File Path</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-white/5">
                      {componentsTable.map((row, i) => (
                        <tr key={i} className="hover:bg-slate-900/30 transition">
                          <td className="py-2.5 px-3 font-bold text-white whitespace-nowrap">
                            {row.component}
                          </td>
                          <td className="py-2.5 px-3 text-slate-300">
                            {row.description}
                          </td>
                          <td className="py-2.5 px-3 text-[#ffb000] text-[11px] whitespace-nowrap">
                            {row.path}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </section>

              {/* 4. API Endpoints */}
              <section className="space-y-2">
                <h2 className="text-sm font-bold text-white flex items-center gap-2">
                  <span className="text-[#ffb000]">4.</span>
                  <span>API Contracts & Endpoints</span>
                </h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                  {apiEndpoints.map((ep, i) => (
                    <div key={i} className="p-3 rounded-xl bg-[#0c0e16] border border-white/5">
                      <span className={`font-bold mr-2 text-[10px] px-1.5 py-0.5 rounded ${ep.method === "POST" ? "bg-[#ffb000]/20 text-[#ffb000]" : "bg-[#00ff66]/20 text-[#00ff66]"}`}>
                        {ep.method}
                      </span>
                      <span className="text-slate-200 font-semibold">{ep.path}</span>
                      <div className="text-[11px] text-slate-400 mt-1">{ep.desc}</div>
                    </div>
                  ))}
                </div>
              </section>
            </>
          )}
        </div>

      </div>

    </div>
  );
}
